intuit/user-data-for-fraud-prevention

README.md

Demo Link in README.md
Fixes #10 
Added Link to the demo in README.md
None
[x] I've tested this in my application using `yarn link` (if applicable)

Added Link to the demo in README.md

---

package.json
tests/unit/common/browserInfoHelper.test.js
tests/unit/hmrc/mtdFraudPrevention.test.js
yarn.lock

Replaced all sinon spies with jest spies resolving issue listed here: https://github.com/intuit/user-data-for-fraud-prevention/issues/7
N/A
[ x] Tests are written and maintain or improve code coverage
[ x] I've tested this in my application using `yarn link` (if applicable)
[x ] You consent to and are confident this change can be released with no regression

Migrate from sinon to jest spies

---

src/js/common/browserInfoHelper.js
tests/unit/common/browserInfoHelper.test.js
tests/unit/mock/MockRTCPeerConnection.js

Fixed the candidate check logic in getDeviceLocalIPAsString function

---

src/js/common/browserInfoHelper.js
src/js/common/globalsUtil.js

Changing the simple function to arrow functions.
Remove unnecessary return statements for code clean up.
...
nothing
...
https://github.com/intuit/user-data-for-fraud-prevention/issues/32
...
[x] I've tested this in my application using `yarn link` (if applicable)

Code clean up removed unnecessary return statements in arrow functions

---

README.md

Add prettier badge to the repo

---

.gitignore
README.md

Improved the contributing section in the readme
Added a few more instructions for new contributors 
Corrected the numbering in the README 
None 
#30 
[x] I've tested this in my application using `yarn link` (if applicable)

chore: updated contributing section in README.md

---

README.md

Updating contributing section

---

README.md

Update demo section in readme with steps for testing intuit#60
Issue intuit#60
...
...
...

Update demo section in readme with steps for testing intuit#60

---

.circleci/config.yml

chore: added coverage generation stage in ci

---

.gitignore
README.md

Added coverage badge to README.md
Added Coveralls code coverage badge to the README
None
To see the coverage Please merge this after #27 
Fixes #19 
[x] I've tested this in my application using `yarn link` (if applicable)

Badges in readme

---

README.md

Update branch for code coverage badge in README.md

---

package.json
src/js/common/browserInfoHelper.js
src/js/common/globalsUtil.js
tests/unit/common/browserInfoHelper.test.js
tests/unit/common/globalUtils.test.js
tests/unit/hmrc/mtdFraudPrevention.test.js

Revert changes "Remove global utils file" as CI build was failing

---

package.json

updating version

---

.circleci/config.yml

Removing auto release for now to fix the CI build failure

---

.circleci/config.yml

Changes to circle config

---

src/js/hmrc/mtdFraudPrevention.js
src/js/index.js
tests/unit/hmrc/mtdFraudPrevention.test.js

Added functions to get the screen and window details.
Nothing
issue #87 

feat: exporting screen and window details in hmrc files

---

yarn.lock

chore(deps): update yarn lock

---

README.md

Resolved Issue #106 (Duplicate NPM Version Badge in Read Me)
Upper row of badges in the read me
...
Nothing
...
Issue #106
...
[X] You consent to and are confident this change can be released with no regression

Removed duplicate NPM version badge in read me. (issue #106).

---

README.md

It is adding the structure in which the code shall be organized within the repository
It will help to segregate different implementations from the common code
It will also allow us to easily expand the code owners in the future.
#17

expected project structure

---

.all-contributorsrc
README.md

Added Contributors on READMe
Contributors are now reflecting on README
...
#108
...

Added contributors on README

---

src/js/common/browserInfoHelper.js
src/js/hmrc/README.md
src/js/hmrc/mtdFraudPrevention.js
tests/unit/common/browserInfoHelper.test.js
tests/unit/hmrc/mtdFraudPrevention.test.js

Add Gov-Client-Browser-JS-User-Agent header to HMRC
Solves #124 

Add Gov-Client-Browser-JS-User-Agent header to HMRC

---

README_SPANISH.md

* Translate `README.md` to Spanish 
* Added to `Other Languages`section in `README.md`
`README.md` now available in spanish
...
[#113 ](https://github.com/intuit/user-data-for-fraud-prevention/issues/113)
...

Added readme in Spanish

---

.releaserc
package-lock.json
package.json

By default, only the published package will contain the version, which is the only place where it is really required, but the updated package.json will not be pushed to the Git repository
This PR adds `@semantic-release/git` which for each release makes a release commit which will be pushed to the remote Git repository.
@skodamarthi We will have to make some git configuration changes to allow this commit to happen:
https://github.com/semantic-release/git#git-authentication
Can you please make the related changes? 
...
...
...

fix: package.json version update on release

---

.releaserc

fix: changelog not getting updated with semantic release
